### PR TITLE
ES6 Proxy (WIP)

### PR DESCRIPTION
**Pull request by noctarius**
I'm working on an ES6 Proxy implementation. Traps can be implemented in JavaScript as in the specification or using a Go struct and the specific function implementations.

Currently still work in progress, some tests are still missing, therefore most probably doesn't work yet in all specified situations.

Anyhow would be happy to get some feedback, as this is my first bigger change to commit back to the official goja repository :-)

I bet there would have to be changes here and there to integrate before it can be merged eventually

### CODE REVIEW

**Comment by orktes** [comment]
Looks like this kinda makes https://github.com/dop251/goja/pull/62 obsolete. I can close the PR, if so.

**Comment by dop251** [comment]
Yes, I think having a Proxy implementation would be better. @noctarius have you tried running any of the tc39 tests against your implementation?

**Comment by noctarius** [comment]
No not yet, still plenty of invariants are missing. Adding them at the moment together with some tests. Right now it is about comments on the code and style and if something should be changed. I'll go ahead and do further work on it though :)

PS: background for the implementation (and especially the go-native side) is running multiple goja instances as app isolation level and using proxies (with security interceptors) to transition between the instances and route data.

**Comment by orktes** [comment]
@noctarius no problem! Just made is a quick hack to make goja usable in my project :)

**Comment by noctarius** [comment]
Still working on it, just was a bit busy during the last days preparing some conference talks :)

**Comment by PaluMacil** [comment]
This is an exciting idea, @noctarius but I am not familiar with a lot of the terms (what you mean by it being a proxy, traps, what you mean in regards to the invariants, etc) but perhaps I'll eventually learn enough to assist more with projects like Goja. I really like the idea of Goja and like ES6 support tenfold more! I wish we would see more expert community involvement assisting you with things like this.

**Comment by noctarius** [comment]
The proxy is just the struct representing the ES6 Proxy as being defined in the spec. The traps are the interceptors for specific methods (also known hooks). If any of those are defined, they'll intercept the original method call and can either do something completely different from actually being defined in the target object or they can do additional stuff (like logging). The invariants are the checks being defined in the spec of what is legal for a proxy trap to do or not. Anyways, the current implementation can completely work around any of those invariants when traps being defined in go rather than JS. This is for the reason, I actually use proxies to intercept calls between different goja VM instances for isolation and security reasons :)

**Comment by PaluMacil** [comment]
@noctarius I've been checking back on this a couple times / week to see if there is any more progress as ES6 would be truly extraordinary in Goja. I started to look through code to see if I could help, and while it might still be a bit over my head, I think I understand more and might be able to help if I practice by perhaps starting with some PRs to goja on Annex B functionality. Is there likelihood of more ES6 progress soon? Once I attempt some other work to get more familiar with Goja, would you benefit from some assistance on this project, or are you far enough along that you might be better off completing it yourself?

**Comment by noctarius** [comment]
@dop251 I see you picked up where I left off. Appreciated! After the startup failed, I unfortunately haven't had time to work on it anymore. Our new system uses a duktape wrapper for a bit more control over the way the JS code is executed (fully sandboxed), but I have another thing I'd probably like to use goja for. I may come back, but I'm glad you picked it up and make it nice and working :)

**Comment by dop251** [comment]
Yeah, I didn't realise how much the internal specification of ES6 was different from ES5... Turns out it requires a lot more work than I initially anticipated.

**Comment by dop251** [comment]
Now merged into es6 branch.

**Comment by noctarius** [comment]
👍

**Pull request closed without merging**
