### PR TITLE
add go module support

### PR DESCRIPTION
**Pull request by choleraehyq**
@dop251 PTAL

Signed-off-by: Cholerae Hu <choleraehyq@gmail.com>

### CODE REVIEW

**Comment by choleraehyq** [comment]
@dop251 Could you please take a look? Thanks.

**Comment by dop251** [comment]
Why do you need this?

**Comment by choleraehyq** [comment]
For now, we don't manage the dependencies of goja at all. It's not safe if any of the dependencies do an incompatible upgrade.

**Comment by PaluMacil** [comment]
This would help a lot, @dop251 It's how you can pin to a particular release version of dependencies, allowing others to use goja in serious projects without being forced to vendor it. This is the official way of managing dependencies in Go 1.13 and it would be a great thing to see adopted.

**Comment by twitchyliquid64** [comment]
+1, please consider merging this.

**Comment by twitchyliquid64** [comment]
As an example of why this might be useful, the README currently says:

> Note, the last working commit is https://github.com/tc39/test262/commit/1ba3a7c4a93fc93b3d0d7e4146f59934a896837d. The next commit made use of template strings which goja does not support.

If you use go modules, you could tag the last working commit with something like `v0.3.2`, and by default your users who `go get` will download that version.

Users who want to follow the README instructions would need to do `go get github.com/dop251/goja@1ba3a7c4a93fc93b3d0d7e4146f59934a896837d`, which would mean they are pinned to that version even if only the minor/patch semver would change.

**Comment by cemremengu** [comment]
@dop251 would you like to merge this please so we can take advantage of go mod?

**Comment by johanstokking** [comment]
@dop251 please see also https://blog.golang.org/using-go-modules

**Comment by tommyo** [comment]
gomod has become the default dependency management system in 1.16, and GOPATH support will be disabled in 1.17. It's time.

[The Go Blog: New module changes in Go 1.16](https://blog.golang.org/go116-module-changes)

Although at this point this commit may be behind. Easier probably to just run `go mod init` and `go get` for each dependency.

**Comment by PaluMacil** [comment]
@dop251 If you have any questions on this or want to discuss, I'm happy to have either a voice or text chat in your timezone preference or can respond to any questions here.

Also, I can't make a PR with a tag, but I'd be happy to add an issue that recommends some version tags if you're interested in marking a couple versions and could even PR a changelog for those versions based upon commits. I would go back, research a couple commits that seem to be relevant and list some git commands I recommend you run and push. Since you aren't committing to an API yet, I recommend version numbers in the v0.x range.

**Pull request closed without merging**
