### PR TITLE
implement escape/unescape

### PR DESCRIPTION
**Pull request by holiman**
Go-ethereum recently switched to Goja from Otto, and received a report that `escape`/`unescape` is not available any more. 
This is apparently already known: https://github.com/dop251/goja/issues/39 
This PR implements those, and the code is taken from the Otto implementation (which is MIT licensed).
 
When testing this, I noticed that the Otto implementation is not compliant with the [specification](https://tc39.es/ecma262/#sec-escape-string), in that the `@`-character was escaped, which it should not be. The code in this PR has been modified to be compliant with the standard.

### CODE REVIEW

**Comment by dop251** [comment]
Unfortunately this is not quite correct, you cannot just return the result of `unescape` as `asciiString` as it may contain non-ASCII characters.

I have written my own implementation and shall push shortly.

**Comment by orgmesh** [comment]
@dop251 Dimitry, regarding the escape/unescape issue, can you advise which version of geth we can run to avoid it?

**Comment by dop251** [comment]
I'm not sure what geth is but my guess would be the next upcoming version :)

**Comment by holiman** [comment]
Correct!

**Pull request closed without merging**
