### PR TITLE
DynamicObject&DynamicArray can be shared between runtimes

### PR DESCRIPTION
**Pull request by vanishs**
now, TypeError is make in correct (*rumtime)

### CODE REVIEW

**Comment by vanishs** [comment]
@dop251 Is there anything wrong with this code that needs to be improved?

**Comment by dop251** [comment]
See the mentioned commit. It should provide the functionality you're after. Let me know if there is any problem.

**Comment by vanishs** [comment]
@dop251 I have a complex and large json read-only object that needs to be shared between each runtime to save memory and cpu usage. Now I made some changes to make DynamicObject/DynamicArray implement this function

**Comment by vanishs** [comment]
Sorry, I just saw close pr on my phone just now, but I didn't see you commit the code. Now it seems to meet my current needs. thanks.

**Pull request closed without merging**
