### PR TITLE
Add Error() and String() to InterruptedError

### LINKED ISSUE #50: InterruptedError should also implement String()
And return the string representation of `iface`
Otherwise, for every error we will need to check if it is InterruptedError and treat it differently.

### PR DESCRIPTION
**Pull request by slavikm**
fixes #50

### CODE REVIEW

**Comment by dop251** [comment]
InterruptedError extends Exception which has stack trace. If your changes are applied this stacktrace would become inaccessible. I would extract the code that prints stacktrace and call it from both Exception and InterruptedError.

**Comment by slavikm** [comment]
@dop251 not sure I understand the difference re stack between `String()` and `Error()`. Why is `Exception.Error()` not iterating and printing the entire stack?

**Comment by dop251** [comment]
Error() is a short single-line version because that's what's used by fmt and you don't want to mess the output with multi-line stacktrace. If you need the stacktrace you use String().

**Comment by dop251** [comment]
Are you still working on it @slavikm ?

**Comment by slavikm** [comment]
Oops, sorry. Yes, will push ASAP.

**Pull request merged**
