### PR TITLE
ExportTo shouldn't just set int's to zero instead it should error out

### PR DESCRIPTION
**Pull request by MStoykov**

### CODE REVIEW

**Comment by dop251** [comment]
What do you mean by "the code that does this also is used for array indexes"? Which code and where is it used?

I think that conversion should only succeed when there is no loss of information (and the reverse conversion is possible). Not sure what I was thinking when writing this 😄 Besides, you can emulate the current behaviour by checking for error and assigning a zero or a rounded up value whereas the opposite is not possible.

**Comment by MStoykov** [comment]
> What do you mean by "the code that does this also is used for array indexes"? Which code and where is it used?

Sorry I wasn't more explicit - `toInt64` seems to be used for array indexing, so even if we wanted to fix that ... it would've been a problem :(. (I did try)

But yeah I agree that `ExportTo` should probably be as strict as possible, and this code is from the initial commit, possibly from otto? 

What are we doing about the test? should I just fix what it expects and rebase so we can merge this?

**Comment by dop251** [comment]
`toInt64` itself does not need to be changed, however I'm having second thoughts about what I said earlier... Neither Go, nor ECMAScript detect integer overflows, i.e. it is perfectly ok to do `i := 333; b := int8(i)` in Go (interestingly it's not ok for constants) and likewise assigning `333` to an item in an `Uint8Array`in JS, both result in `77` being assigned. Same goes for floats, they are truncated when converted to int. 

Perhaps, ExportTo() should do the same, i.e. truncate values on overflow?

**Comment by MStoykov** [comment]
To be honest I don't have a ... hard feeling on whether ExporTo should only work if there is no loss of information or not. 

Arguably there could be ExportTo and ExportToStrict(or ExporTo can be the strict and there could be a not so strict version). This also will mean a stricter version of `toReflectValue`. Also arguably even now it needs more checks because we are converting to int64 and than golang converts it to int8 which might truncate it ... 

I have the feeling that from ... implementation complexity and consistency making it truncate the float will probably be the easiest and most consistent with the other already occurring truncations :man_shrugging:. Also, it will likely break less code than my current change ... where maybe the use case is such that taking a 0 instead of the truncated values didn't actually break the code. 

While I would argue there will be a good reason for there being a way to tell goja that you want an `ExportTo` like operation to fail if it's losing information, I would argue this can be done in the user's code instead of inside goja. And we can always add `ExportToStrict` :D

**Comment by dop251** [comment]
I believe this is the most appropriate way to handle it.

**Pull request closed without merging**
